### ISSUE TITLE
README example not working

### ISSUE THREAD

**Issue by mohit1337** [elmoiv/azapi#5]
I tried with python 3.6.9

```

>>> import azapi
>>> Artist = azapi.AZlyrics()
>>> lyric = Artist.getLyrics("Taylor Swift", "Bad Blood", save=False)
Traceback (most recent call last):
  File "/home/mohit/.virtualenvs/spotify/lib/python3.6/site-packages/azapi/azapi.py", line 71, in getLyrics
    artist = filtr(str(htmlFindAll(page)('div', class_='lyricsh')[0])[29:-23], True)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohit/.virtualenvs/spotify/lib/python3.6/site-packages/azapi/azapi.py", line 75, in getLyrics
    raise Exception('Artist or Title not found!')
Exception: Artist or Title not found!
>>> 

```

**Comment by elmoiv** [comment]
Project was redone from scratch. (V 3.0)
I updated examples and tests too. Check them out :)
